### ISSUE TITLE
bug: <leader>gg cant work when not in git root

### ISSUE THREAD

**Issue by wuxiao889** [folke/snacks.nvim#80] opened 2024-11-15 11:35 UTC
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Centos 7

### Describe the bug

Before updating to LazyVim 13.3, I was using the latest version 12. The <leader>gg command could be opened in any directory and would adjust its position based on the current directory. However, after the update, Lazygit cannot be opened outside of a Git directory and it flashes briefly before exiting. When I open Neovim (nvim) in a Git directory A and then switch the working directory to B within Neovim, Lazygit always opens the Git repository in directory A instead of the project in the current working directory.

### Steps To Reproduce

1. open nvim in a dir without git
2. <leadr>gg
3. lazygit cant open, flash by

### Expected Behavior

1. can open lazygit in anywhere
2. Open Lazygit based on the current Neovim Git directory instead of cwd

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by wuxiao889** [comment] 2024-11-15 11:45
this but dont happen on my mac, i think probably due to os

**Comment by dpetka2001** [comment] 2024-11-15 19:16
I also use LazyVim and it works both in a non-git directory and when opening a file in another git repo. What does `verbose nmap <leader>gg` show?

**Comment by folke** [comment] 2024-11-16 06:29
I just pushed an update where the terminal will remain open in case there were errors.

Closing for now since I can't reproduce.

**Closed by folke** 2024-11-16 06:29 UTC
Labels: bug

**Comment by wuxiao889** [comment] 2024-11-18 02:28
1. can open lazygit in anywhere
I fix it by update lazygit
3. Open Lazygit based on the current Neovim Git directory instead of cwd
I found it because of my error snacks config
