### ISSUE TITLE
bug: zen mode freezing on certain lines

### ISSUE THREAD

**Issue by aquarockslug** [folke/snacks.nvim#278] opened 2024-12-13 10:29 UTC
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Arch Linux WSL

### Describe the bug

I was writing code in zen mode and nvim froze. I restarted nvim and noticed that it always freezes on the same line. I reproduced the code to only have the parts that make it freeze.

### Steps To Reproduce

1. create a javascript file and copy this code into it:
const a = () => null;
const b = () => 
&emsp;null;
const c = () => null
2. turn on zen mode with :lua Snacks.zen{}
3. put the cursor on the first line

### Expected Behavior

nvim shouldn't freeze

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

local use_treesitter = true

require("lazy.minit").repro({
  spec = {
    {
      "folke/snacks.nvim",
      opts = {
        dim = {
          scope = {
            treesitter = { enabled = use_treesitter },
          },
        },
      },
    },
    {
      "nvim-treesitter/nvim-treesitter",
      opts = {
        auto_install = true,
      },
    },
  },
})

local js = [[
const a = () => null;
const b = () =>
 null;
const c = () => null
]]

vim.schedule(function()
  vim.cmd("rightbelow vsplit | enew")
  vim.api.nvim_buf_set_lines(0, 0, -1, false, vim.split(js, "\n"))
  vim.bo.modified = false
  vim.cmd("setf javascript")
  if use_treesitter then
    vim.treesitter.start()
  end
  Snacks.zen()
end)
```

**Comment by folke** [comment] 2024-12-13 13:37
And do you have treesitter for js?

**Comment by folke** [comment] 2024-12-13 14:11
I updated the repro for testing. Can you please make it so that it's reproducible?

**Comment by folke** [comment] 2024-12-14 21:22
I made some changes related to scope detection which was likely the cause of this.
Closing, but do let me know if you'd see this again.

**Closed by folke** 2024-12-14 21:22 UTC
Labels: bug
