### ISSUE TITLE
bug: Something to do with folding.

### ISSUE THREAD

**Issue by Fausto-Korpsvart** [folke/snacks.nvim#53] opened 2024-11-09 18:56 UTC
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.11.0-dev+1116-gb7e1bbfb5

### Operating system/version

Fedora 41

### Describe the bug

Hello, Folke.

I recently wrote something on Reddit related to how to disable Snacks due to it causing slowness and sometimes freezing in my setup.
Well, I've been checking my settings and I have these options enabled:
```lua
foldcolumn = ‘0’,
foldenable = true,
foldlevel = 99,
foldlevelstart = 0,
foldmethod = ‘marker’,
```
After disabling these options, everything is back to normal.

I noticed it since I installed LazyVim from scratch and, when I added my own options, and without adding any other plugin, I tried to fold some code, Neovim suddenly froze, that gave me the idea to disable them, after doing that I didn't have the Neovim freezing problem anymore, only when trying to fold code that has already been folded before, in any case, it seems that the freezing is related to the folding.

Now, I'm noticing that Neovim, when using the default LazyVim configuration, uses a lot of resources, processing and memory are a bit shot, when using Neovim without LazyVim, the resource usage is normal.

### Steps To Reproduce

In the description.

### Expected Behavior

Neovim should not be slow or freeze.

**Comment by dpetka2001** [comment] 2024-11-09 20:17
Well there are quite a few UI features that need to refresh to provide relevant information (like lualine, statuscolumn, etc) and that need to redraw in order to show the correct information. 

I have a really old laptop (Dell 2013, Intel Core i5, 6GB Ram, old 5400rpm HDD) and the usage with `nvim --clean` is 8MB RAM and 0%CPU, whereas my LazyVim configuration takes 42MB RAM and fluctuates between 3-5% CPU (with spikes in the moment of up to 10%). The most recources (RAM, CPU) are usually requested by the language server at hand. Even `lua_ls` can be pretty resource hungry (408MB RAM and up to 100% CPU when indexing a workspace which consists of several open buffers and then it falls down to 0-1% after it's finished indexing) and I've heard even worse things about Typescript or even Python servers. 

So, in my experience it's usually external sources that require most of the resources, not Neovim (and the extra configuration that Neovim distros provide, which they indeed add some amount of overhead compared to just vanilla Neovim)  itself.

And those numbers are on a really old laptop like I've already mentioned. I can imagine things are much better on newer machines.

**Comment by folke** [comment] 2024-11-09 21:18
There is for sure something wrong with treesitter folds in LazyVim right now.
Still haven't found what's causing issues. 
Pretty sure it's not related to snacks.
Whenever I try closing a treesitter fold, my neovim locks up.

**Comment by folke** [comment] 2024-11-09 21:19
I have this with stock LazyVim btw. No other customisations.

**Comment by folke** [comment] 2024-11-09 21:20
And it also locked up with v12.x. Probably something that changed on Neovim nightly.

**Comment by folke** [comment] 2024-11-09 21:21
Can confirm that on Neovim stable, the issue is gone

**Comment by Fausto-Korpsvart** [comment] 2024-11-09 21:41
I understand, I related it to Snack because before the integration everything was fine, and it was the only new thing in the configuration.

I have not tested with Neovim stable, if you have already tested then there is surely something wrong with Neovim Nightly.

Thanks for clarifying this, Folke, I will test with the stable version until this is fixed.

Should I close it, or will you close it when it's fixed?

**Comment by folke** [comment] 2024-11-09 21:43
Keep it open, since in a minimal repro with treesitter folds on nightly, it does not lock up.
So it must be that in combination with someting else in lazyvim.

**Comment by folke** [comment] 2024-11-09 21:53
Super weird, but it seems to be caused by LSP. 
If I do `:LspStop`, then folding works again.

**Comment by dpetka2001** [comment] 2024-11-09 21:57
I was just about to write the same. I did a minimal repro and when I commented out `require("lspconfig").lua_ls.setup()` it stopped occuring. I didn't test with other LSP servers.

**Comment by folke** [comment] 2024-11-09 22:01
Casued by https://github.com/neovim/neovim/issues/31129

Fixed already in https://github.com/neovim/neovim/commit/4b001f297ae29654b86eccd4dde72b2cc314ca01

Closing.

**Comment by dpetka2001** [comment] 2024-11-09 22:02
Cool will wait for tomorrow's nightly then :smile:

**Closed by folke** 2024-11-09 22:01 UTC
Labels: bug

**Comment by Fausto-Korpsvart** [comment] 2024-11-09 22:05
> Casued by [neovim/neovim#31129](https://github.com/neovim/neovim/issues/31129)
> 
> Fixed already in [neovim/neovim@4b001f2](https://github.com/neovim/neovim/commit/4b001f297ae29654b86eccd4dde72b2cc314ca01)
> 
> Closing.

Thanks Folke, and I'm sorry I blamed Snacks xD

**Comment by folke** [comment] 2024-11-09 22:05
Btw, my very useful fish `slay` function for testing things like this :)

```fish
# Defined in /home/folke/.config/fish/functions/slay.fish @ line 1
function slay
    # Get list of high CPU usage processes (pid, cpu%, command)
    top -b -n1 | awk 'NR>7 {if($9 > 90) print $1, $9, $12}' | while read pid cpu command
        echo "Killing PID $pid ($command) for high CPU usage: $cpu%"
        kill -9 $pid
    end
end
```

**Comment by Fausto-Korpsvart** [comment] 2024-11-09 22:21
> Well there are quite a few UI features that ...

@dpetka2001, My laptop has 16GB of RAM, a Ryzen 7 and 1TB on an M.2, and it's not that old, so it should be able to run Neovim open in a terminal.

And I'm aware that LSP and other external sources and their configurations increase resource usage, but not to the point of having only one terminal open with Neovim and the coolers spinning so much that the noise is noticeable, and the temperature rises too much xD

Maybe with tomorrow's Nightly update this will be resolved, for now, to finish the job, I'll try the stable version.
